output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

# for debugging purposes
output.console:
  enabled: false
  pretty: true

filebeat.config:
  inputs:
    enabled: true
    path: /usr/share/filebeat/inputs.d/*.yml
    reload.enabled: false
    reload.period: 10s
