version: "2.4"
services:
  elasticsearch:
    container_name: atm-elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    mem_limit: ${ES_MEM_LIMIT}
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - atm-elastic
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:${ELASTIC_PASSWORD}", "http://localhost:9200/_cat/health"]
      retries: 10
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"

  kibana:
    container_name: atm-kibana
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}"
    ports:
      - 5601:5601
    networks:
      - atm-elastic
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/kibana.yml
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
      retries: 10
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"

  logstash:
    container_name: atm-logstash
    image: "docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}"
    ports:
      - 5000:5000
      - 5044:5044
    networks:
      - atm-elastic
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/

  filebeat:
    container_name: atm-filebeat
    image: "docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}"
    networks:
      - atm-elastic
    depends_on:
      - elasticsearch
      # - logstash
    user: root
    # command: filebeat -e -E output.elasticsearch.username=elastic -E output.elasticsearch.password=${ELASTIC_PASSWORD} -strict.perms=false
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # add prospectors to this directory and they will be dynamically loaded
      - ./filebeat/inputs.d/:/usr/share/filebeat/inputs.d/
      # persist the registry file between restarts, so to avoid data duplication
      #- fb-data:/usr/share/filebeat/data/
      # ATM
      - ../test/:/var/log/atm/

volumes:
  es-data:
  fb-data:

networks: {atm-elastic: {}}
