version: "2.4"
services:
  atm-elasticsearch:
    container_name: atm-elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    mem_limit: ${ES_MEM_LIMIT}
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - atm-elastic
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:${ELASTIC_PASSWORD}", "http://localhost:9200/_cat/health"]
      retries: 10
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"

  atm-kibana:
    container_name: atm-kibana
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}"
    ports:
      - 5601:5601
    networks:
      - atm-elastic
    depends_on:
      - atm-elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/kibana.yml
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
      retries: 10
    environment:
      ELASTICSEARCH_URL: "http://atm-elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
volumes:
  es-data:
  # fb-data:

networks: {atm-elastic: {}}
